# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb707e1b89c8899593062756f7955abfb54168a52d2ccd1953d5a2942d6ce265b6febb1c350c7085ceaf7bc38242fce91c5a26144e275b7bf60a7da7c5a2b4d

test:
  secret_key_base: 3547ff03e73adb045722c2203eac7fecc9baefd154248949eb16fe306844ff60f65617063c58bbe6b04a5d411e6af2962efd9cdca693c67dfbfec5d3fdf2cc8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
